// Builds the PR body from Claude's final JSON result plus the issue number, again
// entirely through process.env / file reads rather than templated shell text.
import fs from "node:fs";

const { ISSUE_NUMBER } = process.env;

let summary = "Automated fix generated by Claude Code. See the diff for details.";
try {
  const raw = fs.readFileSync("/tmp/claude-output.json", "utf8");
  const parsed = JSON.parse(raw);
  if (typeof parsed.result === "string" && parsed.result.trim()) {
    summary = parsed.result.trim();
  }
} catch {
  // No usable Claude output; fall back to the default summary above.
}

const body = `Fixes #${ISSUE_NUMBER}

## Summary
${summary}

## Test confirmation
The repository test suite (\`npm test\`) passed on this branch.

_This pull request was created automatically by Claude via GitHub Actions._
`;

fs.writeFileSync("/tmp/pr-body.md", body);
