import { runResolverAgent } from "./agent.js";
import { config } from "./config.js";
import {
  commentOnIssue,
  fetchIssue,
  getDefaultBranch,
  openPullRequest,
  removeLabel,
} from "./github.js";
import { commitAll, createIssueBranch, ensureWorkspace, hasChanges, pushBranch } from "./git.js";
import { logger } from "./logger.js";
import { installDependencies } from "./tools.js";
import type { RepoRef } from "./types.js";

export interface ProcessIssueResult {
  success: boolean;
  prUrl?: string;
  reason?: string;
}

export async function processIssue(repo: RepoRef, issueNumber: number): Promise<ProcessIssueResult> {
  const label = `issue #${issueNumber} (${repo.owner}/${repo.repo})`;
  try {
    const issue = await fetchIssue(repo, issueNumber);

    await commentOnIssue(
      repo,
      issueNumber,
      "🤖 Automated resolution in progress — I'm investigating this issue and will open a pull request if I find a fix.",
    );

    const defaultBranch = await getDefaultBranch(repo);
    const workspaceDir = await ensureWorkspace(repo, defaultBranch);
    const branchName = `fix/issue-${issueNumber}-patch`;
    await createIssueBranch(workspaceDir, branchName, defaultBranch);

    const install = await installDependencies(workspaceDir);
    logger.info("Installed dependencies", { label, success: install.success });
    if (!install.success) {
      logger.warn("Dependency install failed; agent will attempt to continue", { label });
    }

    logger.info("Running resolver agent", { label, branchName });
    const result = await runResolverAgent(issue, workspaceDir);

    if (!result.success || !(await hasChanges(workspaceDir))) {
      const reason = result.reason ?? "No passing fix was produced.";
      logger.warn("Agent did not produce a mergeable fix", { label, reason });
      await commentOnIssue(
        repo,
        issueNumber,
        [
          "🤖 I was unable to automatically resolve this issue.",
          "",
          `**Reason:** ${reason}`,
          "",
          result.testOutput ? `<details><summary>Last test output</summary>\n\n\`\`\`\n${result.testOutput.slice(0, 3000)}\n\`\`\`\n</details>` : "",
          "",
          "A maintainer will need to take a look manually.",
        ].join("\n"),
      );
      return { success: false, reason };
    }

    await commitAll(workspaceDir, `Fix #${issueNumber}: ${issue.title}\n\nAutomated fix generated by the Resolver agent.`);
    await pushBranch(workspaceDir, branchName, repo);

    const prUrl = await openPullRequest({
      repo,
      head: branchName,
      base: defaultBranch,
      issueNumber,
      title: `Fix: ${issue.title}`,
      summary: result.summary,
      testOutput: result.testOutput,
    });

    await removeLabel(repo, issueNumber, config.triggerLabel);

    await commentOnIssue(
      repo,
      issueNumber,
      `✅ I opened a pull request with a fix: ${prUrl}`,
    );

    logger.info("Resolved issue", { label, prUrl });
    return { success: true, prUrl };
  } catch (err) {
    const reason = (err as Error).message;
    logger.error("Failed to process issue", { label, error: reason });
    try {
      await commentOnIssue(
        repo,
        issueNumber,
        `🤖 Something went wrong while attempting an automated fix: ${reason}\n\nA maintainer will need to take a look manually.`,
      );
    } catch (commentErr) {
      logger.error("Failed to post failure comment", { label, error: (commentErr as Error).message });
    }
    return { success: false, reason };
  }
}
